// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://swvdtotpssmiahlxaznt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN3dmR0b3Rwc3NtaWFobHhhem50Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA2NTc5MzksImV4cCI6MjA2NjIzMzkzOX0.d9hpoUtp33j2F7E2cy3-riI28Bx5vrtXg97NuKQs6v4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);